Story screen uses JSON files
TurningWheel/Barony pull request #611
Opened 2022-01-05 06:31 UTC by SheridanR

change minimap colors
fix player bobbing while using console

Signed-off-by: SheridanR <sheridan.rathbun@gmail.com>

2022-01-16 14:30 UTC, WALLOFJUSTICE requested changes

2022-01-16 21:59 UTC, SheridanR commented on src/menu.cpp
> -			LobbyHandler.settings_crossplayEnabled = false;
I suppose not, I'd rather not add it back though so it's best just to remember where it was when I canned it

2022-01-17 00:09 UTC, WALLOFJUSTICE commented on src/menu.cpp
> -			LobbyHandler.settings_crossplayEnabled = false;
Can you add the equivalent of this back in to the new settings?

2022-01-17 00:18 UTC, SheridanR commented on src/actplayer.cpp
> +						messageLocalPlayersColor(color, MESSAGE_WORLD, language[537]);
It was defined the other way, but then I accidentally put all the args in the wrong order 🤦‍♂️ easier to just switch the parameters as a fix.

2022-01-17 01:40 UTC, SheridanR commented on src/menu.cpp
> -			LobbyHandler.settings_crossplayEnabled = false;
done

2022-01-17 01:45 UTC, merged